# Generated by Django 4.2 on 2023-04-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='Vip',
            field=models.BooleanField(blank=True, verbose_name='Выполнено'),
        ),
    ]
