# Generated by Django 4.2 on 2023-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reestr_1_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='Vip',
            field=models.BooleanField(null=True, verbose_name='Выполнено'),
        ),
    ]
