# Generated by Django 4.2 on 2023-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reestr_1_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr_1',
            name='vidano',
            field=models.CharField(blank=True, max_length=150, verbose_name='Кем выдано'),
        ),
    ]
