# Generated by Django 4.2 on 2023-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reestr_1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='Vip',
            field=models.BooleanField(default='Нет', null=True, verbose_name='Выполнено'),
        ),
    ]
