# Generated by Django 4.2 on 2023-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_reestr_1_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='Vip',
            field=models.BooleanField(default=False, null=True, verbose_name='Выполнено'),
        ),
    ]
