# Generated by Django 4.2 on 2023-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reestr_1_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reestr1Summary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество заявлений',
                'verbose_name_plural': 'Количество заявлений',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.reestr_1',),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Дата регистрации заявления'),
        ),
    ]
