# Generated by Django 4.2 on 2023-05-14 14:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reestr1summary_alter_reestr_1_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reestr1summary',
            options={'verbose_name': 'Количество заявлений на получение санитарно-эпидемиологического заключения, лицензии, свидетельства о государственной регистрации продукции', 'verbose_name_plural': 'Количество заявлений на получение санитарно-эпидемиологического заключения, лицензии, свидетельства о государственной регистрации продукции'},
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='Otd',
            field=models.CharField(choices=[('Гигиена детей и подростков', 'Гигиена детей и подростков'), ('Гигиена труда', 'Гигиена труда'), ('Эпид. отдел', 'Эпид. отдел'), ('Отдел санитарно-эпидемиологических заключений', 'Отдел санитарно-эпидемиологических заключений')], default='Гигиена детей и подростков', max_length=120, verbose_name='Отдел исполнитель'),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='namber',
            field=models.CharField(default=core.models.func, max_length=15, verbose_name='Номер заявления'),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='sp',
            field=models.CharField(choices=[('ПГУ', 'ПГУ'), ('Нарочным', 'Нарочным'), ('Почта', 'Почта')], default='ПГУ', max_length=200, verbose_name='Способ направления документов'),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='vid',
            field=models.CharField(choices=[('Проект', 'Проект'), ('Производство', 'Производство'), ('Лицензия', 'Лицензия'), ('Санитарно-защитная зона', 'Санитарно-защитная зона'), ('Свидетельство о государственной регистрации', 'Свидетельство о государственной регистрации')], default='Проект', max_length=50, verbose_name='Вид деятельности'),
        ),
    ]
