# Generated by Django 4.2 on 2023-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reestr1summary_options_alter_reestr_1_otd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='vid',
            field=models.CharField(default='Проект', max_length=50, verbose_name='Вид деятельности'),
        ),
    ]
