# Generated by Django 4.2 on 2023-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reestr_1_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='date_rendering',
            field=models.DateTimeField(verbose_name='Дата оказания государственной услуги'),
        ),
    ]
