# Generated by Django 4.2 on 2023-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_reestr_1_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='date_creation',
            field=models.DateTimeField(blank=True, verbose_name='Дата регистрации заявления'),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='date_rendering',
            field=models.DateTimeField(blank=True, verbose_name='Дата оказания государственной услуги'),
        ),
    ]
