# Generated by Django 4.2 on 2023-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_reestr_2_fam_remove_reestr_2_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_2',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Дата регистрации заявления'),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='date_rendering',
            field=models.DateTimeField(verbose_name='Дата оказания государственной услуги'),
        ),
    ]
