# Generated by Django 4.2 on 2023-05-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_namber'),
    ]

    operations = [
        migrations.AddField(
            model_name='namber',
            name='Nom2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.reestr_2', verbose_name='Номер 2'),
        ),
        migrations.AlterField(
            model_name='namber',
            name='Nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.reestr_1', verbose_name='Номер 1'),
        ),
    ]
