# Generated by Django 4.2 on 2023-05-18 19:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_namber_nom_alter_namber_nom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_2',
            name='SEZ1',
            field=models.CharField(blank=True, max_length=27, verbose_name='Номер санитарно-эпидемиологического заключения'),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='namber',
            field=models.CharField(default=core.models.func2, max_length=15, verbose_name='Номер заявления'),
        ),
    ]
