# Generated by Django 4.2 on 2023-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_reestr_2_sez1_alter_reestr_2_namber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reestr2Summary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество заявлений на выдачу решений об установлении санитарно-защитной зоны',
                'verbose_name_plural': 'Количество заявлений на выдачу решений об установлении санитарно-защитной зоны',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.reestr_2',),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='Type_application',
            field=models.CharField(choices=[('Установление санитарно-защитной зоны', 'Установление санитарно-защитной зоны'), ('Изменение санитарно-защитной зоны', 'Изменение санитарно-защитной зоны'), ('Сокращение санитарно-защитной зоны', 'Сокращение санитарно-защитной зоны')], max_length=100, verbose_name='Тип заявления'),
        ),
    ]
