# Generated by Django 4.2 on 2023-05-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reestr2summary_alter_reestr_2_type_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='reestr_2',
            name='Vip',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Выполнено'),
        ),
    ]
