# Generated by Django 4.2 on 2023-06-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reestr_2_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_2',
            name='Object',
            field=models.CharField(choices=[('Действующий', 'Действующий'), ('Проектируемый', 'Проектируемый'), ('Реконструированный', 'Реконструированный')], default='Действующий', max_length=50, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='SEZ2',
            field=models.CharField(choices=[('Роспотребнадзор', 'Роспотребнадзор'), ('Иная организация', 'Иная организация')], default='Роспотребнадзор', max_length=40, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='Type_application',
            field=models.CharField(choices=[('Установление санитарно-защитной зоны', 'Установление санитарно-защитной зоны'), ('Изменение санитарно-защитной зоны', 'Изменение санитарно-защитной зоны'), ('Сокращение санитарно-защитной зоны', 'Сокращение санитарно-защитной зоны')], default='Установление санитарно-защитной зоны', max_length=100, verbose_name='Тип заявления'),
        ),
        migrations.AlterField(
            model_name='reestr_2',
            name='cl',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=2, verbose_name='Класс опасности'),
        ),
    ]
