# Generated by Django 4.2 on 2023-06-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_reestr_2_object_alter_reestr_2_sez2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Namber',
        ),
    ]
