# Generated by Django 4.2 on 2023-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_namber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reestr_1',
            name='dejat',
            field=models.CharField(max_length=200, verbose_name='Наименование деятельности/Причина переоформления'),
        ),
        migrations.AlterField(
            model_name='reestr_1',
            name='vid',
            field=models.CharField(choices=[('Проект', 'Проект'), ('Производство', 'Производство'), ('Лицензия', 'Лицензия'), ('Санитарно-защитная зона', 'Санитарно-защитная зона'), ('Свидетельство о государственной регистрации', 'Свидетельство о государственной регистрации'), ('Переформление лицензии', 'Переформление лицензии'), ('Переформление СЭЗ', 'Переформление СЭЗ'), ('Переформление Свидетельства', 'Переформление Свидетельства')], default='Проект', max_length=50, verbose_name='Вид деятельности'),
        ),
    ]
