# Generated by Django 4.2 on 2023-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADM_REG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название административного регламента')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_ADM/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'Административный регламент',
                'verbose_name_plural': 'Административные регламенты',
            },
        ),
        migrations.CreateModel(
            name='NPA_GOSREG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_GOSREG/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'НПА по государственной регистрации продукции',
                'verbose_name_plural': 'НПА по государственной регистрации продукции',
            },
        ),
        migrations.CreateModel(
            name='NPA_LICENZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_LICENZ/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'НПА по лицензированию',
                'verbose_name_plural': 'НПА по лицензированию',
            },
        ),
        migrations.CreateModel(
            name='NPA_SEZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_SEZ/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'НПА по СЭЗ',
                'verbose_name_plural': 'НПА по СЭЗ',
            },
        ),
        migrations.CreateModel(
            name='NPA_SZZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_SZZ/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'НПА по санитарно-защитным зонам',
                'verbose_name_plural': 'НПА по санитарно-защитным зонам',
            },
        ),
        migrations.CreateModel(
            name='NPA_UVED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_UVED/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'НПА по уведомлениям о начале осуществления предпринимательской деятельности',
                'verbose_name_plural': 'НПА по уведомлениям о начале осуществления предпринимательской деятельности',
            },
        ),
        migrations.CreateModel(
            name='OPT_STAND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('date_creation', models.DateTimeField(blank=True, verbose_name='Дата документа')),
                ('kr_op', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('silk', models.FileField(blank=True, upload_to='KMS_OPT/%Y/%m/%d', verbose_name='Ссылка для скачивания документа')),
            ],
            options={
                'verbose_name': 'Оптимизированные стандарты',
                'verbose_name_plural': 'Оптимизированные стандарты',
            },
        ),
    ]
