# Generated by Django 4.2 on 2023-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KMS_sotr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adm_reg',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='npa_gosreg',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='npa_licenz',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='npa_sez',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='npa_szz',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='npa_uved',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='opt_stand',
            name='kr_op',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
