# Generated by Django 4.2 on 2023-05-21 14:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LIC1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer', models.CharField(blank=True, max_length=60, unique=True, verbose_name='Номер лицензии')),
                ('date_creation', models.DateTimeField(verbose_name='Дата документа')),
                ('licenz', models.CharField(max_length=300, verbose_name='Лицензиат')),
                ('INN', models.IntegerField()),
                ('OGRN', models.IntegerField()),
                ('UR', models.CharField(max_length=300, verbose_name='Юридический адрес лицензиата')),
                ('vid', models.CharField(choices=[('Деятельность в области использования возбудителей инфекционных заболеваний человека и животных (за исключением случая, если указанная деятельность осуществляется в медицинских целях) и генно-инженерно-модифицированных организмов III и IV степеней потенциальной опасности, осуществляемой в замкнутых системах.', 'Деятельность в области использования возбудителей инфекционных заболеваний человека и животных (за исключением случая, если указанная деятельность осуществляется в медицинских целях) и генно-инженерно-модифицированных организмов III и IV степеней потенциальной опасности, осуществляемой в замкнутых системах'), ('Деятельность в области использования источников ионизирующего излучения (генерирующих) (за исключением случая, если эти источники используются в медицинской деятельности).', 'Деятельность в области использования источников ионизирующего излучения (генерирующих) (за исключением случая, если эти источники используются в медицинской деятельности).')], default='Деятельность в области использования возбудителей инфекционных заболеваний человека и животных (за исключением случая, если указанная деятельность осуществляется в медицинских целях) и генно-инженерно-модифицированных организмов III и IV степеней потенциальной опасности, осуществляемой в замкнутых системах.', max_length=500, verbose_name='Вид деятельности')),
                ('mesto', models.CharField(max_length=500, verbose_name='Место осуществления деятельности')),
            ],
            options={
                'verbose_name': 'Лицензии',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='RESH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.CharField(max_length=60, unique=True, verbose_name='Номер Решения')),
                ('date_creation', models.DateTimeField(verbose_name='Дата документа')),
                ('applic', models.CharField(max_length=300, verbose_name='Заявитель (представитель заявителя)')),
            ],
        ),
        migrations.CreateModel(
            name='SEZ1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer', models.CharField(blank=True, max_length=60, unique=True, verbose_name='Номер санитарно-эпидемиологического заключения, лицензии, свидетельства о государственной регистрации продукции')),
                ('date_creation', models.DateTimeField(null=True, verbose_name='Дата документа')),
                ('tipogr', models.CharField(max_length=50, verbose_name='Типографский номер бланка')),
                ('sootv', multiselectfield.db.fields.MultiSelectField(choices=[('СанПиН 1.2.3685-21 "Гигиенические нормативы и требования к обеспечению безопасности и (или) безвредности для человека факторов среды обитания"', 'СанПиН 1.2.3685-21 "Гигиенические нормативы и требования к обеспечению безопасности и (или) безвредности для человека факторов среды обитания"'), ('СанПиН 2.3/2.4.3590-20 "Санитарно-эпидемиологические требования к организации общественного питания населения"', 'СанПиН 2.3/2.4.3590-20 "Санитарно-эпидемиологические требования к организации общественного питания населения"'), ('Переоформление', 'Переоформление')], max_length=500, null=True, verbose_name='Соответствует: ')),
                ('Pereof', models.CharField(blank=True, max_length=30, verbose_name='Номер переоформляемого СЭЗ')),
                ('vidano', models.CharField(blank=True, max_length=150, verbose_name='Кем выдано')),
                ('deistv', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'СЭЗ',
                'verbose_name_plural': 'СЭЗ',
            },
        ),
    ]
