# Generated by Django 4.2 on 2023-05-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reestr_2_vip'),
        ('SANZ_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEZSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество выданных СЭЗ',
                'verbose_name_plural': 'Количество выданных СЭЗ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SANZ_1.sez1',),
        ),
        migrations.CreateModel(
            name='SEZItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('-', '-'), ('Услуга оказана', 'Услуга оказана')], default='-', max_length=150, null=True, verbose_name='Статус')),
                ('LIC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='SANZ_1.lic1', verbose_name='Номер лицензии')),
                ('SEZ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='SANZ_1.sez1', verbose_name='Номер СЭЗ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.reestr_1', verbose_name='Заявление')),
            ],
            options={
                'verbose_name': 'Санитарно-эпидемиологические заключения',
                'verbose_name_plural': 'Санитарно-эпидемиологические заключения',
            },
        ),
        migrations.CreateModel(
            name='RESHItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('-', '-'), ('Услуга оказана', 'Услуга оказана')], default='-', max_length=150, null=True, verbose_name='Статус')),
                ('resh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items1', to='SANZ_1.resh1', verbose_name='Номер СЭЗ')),
                ('sajav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items2', to='core.reestr_2', verbose_name='Номер решения')),
            ],
        ),
    ]
