# Generated by Django 4.2 on 2023-05-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reestr_2_vip'),
        ('SANZ_1', '0002_sezsummary_sezitem_reshitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reshitem',
            name='resh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items1', to='SANZ_1.resh1', verbose_name='Номер решения'),
        ),
        migrations.AlterField(
            model_name='reshitem',
            name='sajav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items2', to='core.reestr_2', verbose_name='Номер заявления'),
        ),
        migrations.AlterField(
            model_name='sezitem',
            name='LIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items2', to='SANZ_1.lic1', verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='sezitem',
            name='SEZ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items1', to='SANZ_1.sez1', verbose_name='Номер СЭЗ'),
        ),
    ]
