# Generated by Django 4.2 on 2023-05-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0003_alter_reshitem_resh_alter_reshitem_sajav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic1',
            name='INN',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lic1',
            name='OGRN',
            field=models.IntegerField(blank=True),
        ),
    ]
