# Generated by Django 4.2 on 2023-05-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reestr_2_vip'),
        ('SANZ_1', '0004_alter_lic1_inn_alter_lic1_ogrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reshitem',
            name='resh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items3', to='SANZ_1.resh1', verbose_name='Номер решения'),
        ),
        migrations.AlterField(
            model_name='reshitem',
            name='sajav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items4', to='core.reestr_2', verbose_name='Номер заявления'),
        ),
    ]
