# Generated by Django 4.2 on 2023-05-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0005_alter_reshitem_resh_alter_reshitem_sajav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sezitem',
            name='LIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_SEZ_LIC', to='SANZ_1.lic1', verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='sezitem',
            name='SEZ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_SEZ', to='SANZ_1.sez1', verbose_name='Номер СЭЗ'),
        ),
    ]
