# Generated by Django 4.2 on 2023-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0006_alter_sezitem_lic_alter_sezitem_sez'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resh1',
            options={'verbose_name': 'Решения', 'verbose_name_plural': 'Решения'},
        ),
        migrations.AddField(
            model_name='resh1',
            name='photo',
            field=models.FileField(null=True, upload_to='pdf/%Y/%m/%d', verbose_name='Скан решения'),
        ),
    ]
