# Generated by Django 4.2 on 2023-06-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0008_resh1_kl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sez1',
            name='Pereof',
        ),
    ]
