# Generated by Django 4.2 on 2023-06-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0009_remove_sez1_pereof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pereoformlen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=200, verbose_name='Номер переоформляемого документа и дата')),
                ('nomer2', models.CharField(max_length=200, verbose_name='Номер нового документа')),
                ('date', models.DateTimeField(verbose_name='Дата новго документа')),
                ('prich', models.CharField(max_length=200, verbose_name='Причина переоформления документа')),
            ],
        ),
        migrations.CreateModel(
            name='SVID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer', models.CharField(max_length=30, unique=True, verbose_name='Номер Свидетельства о государственной регистрации')),
                ('date_creation', models.DateTimeField(verbose_name='Дата документа')),
                ('tipogr', models.CharField(blank=True, max_length=30, verbose_name='Типографский номер бланка')),
                ('obl', models.CharField(max_length=300, verbose_name='Область применения')),
                ('Svid_vid', models.CharField(max_length=500, verbose_name='Сведетельство выдано')),
                ('firm', models.CharField(max_length=200, verbose_name='Фирма получатель')),
                ('Norm', models.CharField(max_length=200, verbose_name='Нормативная документация')),
            ],
        ),
        migrations.AddField(
            model_name='sezitem',
            name='PER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_SEZ_Pere', to='SANZ_1.pereoformlen', verbose_name='Номер переоформленного документа'),
        ),
        migrations.AddField(
            model_name='sezitem',
            name='SV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_SEZ_SVID', to='SANZ_1.svid', verbose_name='Номер свидетельства о государственной регистрации'),
        ),
    ]
