# Generated by Django 4.2 on 2023-06-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0010_pereoformlen_svid_sezitem_per_sezitem_sv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PereSummary',
            fields=[
                ('pereoformlen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SANZ_1.pereoformlen')),
            ],
            bases=('SANZ_1.pereoformlen',),
        ),
        migrations.CreateModel(
            name='LICSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество выданных Лицензий',
                'verbose_name_plural': 'Количество выданных Лицензий',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SANZ_1.lic1',),
        ),
        migrations.CreateModel(
            name='SVIDSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество выданных Свидетельств',
                'verbose_name_plural': 'Количество выданных Свидетельств',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SANZ_1.svid',),
        ),
        migrations.AlterModelOptions(
            name='pereoformlen',
            options={'verbose_name': 'Переоформленные документы', 'verbose_name_plural': 'Переоформленные документы'},
        ),
        migrations.AlterModelOptions(
            name='svid',
            options={'verbose_name': 'Свидетельства о государственной регистрации продукции', 'verbose_name_plural': 'Свидетельства о государственной регистрации продукции'},
        ),
    ]
