# Generated by Django 4.2 on 2023-06-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0011_peresummary_licsummary_svidsummary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PereSummary',
        ),
    ]
