# Generated by Django 4.2 on 2023-06-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SANZ_1', '0012_delete_peresummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lic1',
            name='INN',
        ),
        migrations.RemoveField(
            model_name='lic1',
            name='OGRN',
        ),
        migrations.RemoveField(
            model_name='lic1',
            name='UR',
        ),
        migrations.RemoveField(
            model_name='lic1',
            name='licenz',
        ),
        migrations.RemoveField(
            model_name='lic1',
            name='mesto',
        ),
    ]
