# Generated by Django 4.2 on 2023-05-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_reestr_1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomer1', models.CharField(blank=True, max_length=60, unique=True, verbose_name='Номер письма')),
                ('date_creation', models.DateField(null=True, verbose_name='Дата документа')),
                ('prich', models.CharField(max_length=50, verbose_name='Причина отказа')),
                ('vidano', models.CharField(blank=True, max_length=150, verbose_name='Кем выдано')),
            ],
            options={
                'verbose_name': 'Отказы',
                'verbose_name_plural': 'Отказы',
            },
        ),
        migrations.CreateModel(
            name='OTKItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(choices=[('Отказ в оказании государственной услуги', 'Отказ в оказании государственной услуги')], default='Создан', max_length=150, null=True, verbose_name='Статус')),
                ('otk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='OTKAZ.otk', verbose_name='Номер письма')),
                ('product1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items1', to='core.reestr_1', verbose_name='Заявление')),
            ],
            options={
                'verbose_name': 'Отказы в выдаче документов',
                'verbose_name_plural': 'Отказы в выдаче документов',
            },
        ),
    ]
