# Generated by Django 4.2 on 2023-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTKAZ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTKAZSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Количество отказов в выдаче документов',
                'verbose_name_plural': 'Количество отказов в выдаче документов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('OTKAZ.otk',),
        ),
        migrations.AlterField(
            model_name='otk',
            name='date_creation',
            field=models.DateTimeField(null=True, verbose_name='Дата документа'),
        ),
    ]
