# Generated by Django 4.2 on 2023-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTKAZ', '0003_otkitem_product2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkitem',
            name='status1',
            field=models.CharField(choices=[('-', '-'), ('Отказ в оказании государственной услуги', 'Отказ в оказании государственной услуги')], default='-', max_length=150, null=True, verbose_name='Статус'),
        ),
    ]
