# Generated by Django 4.2 on 2023-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTKAZ', '0004_alter_otkitem_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otk',
            name='vidano',
            field=models.CharField(blank=True, max_length=150, verbose_name='Исполнитель'),
        ),
    ]
